### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by robertvazan** [MutopiaProject/MutopiaProject#1018]
Go to http://www.mutopiaproject.org/, click anything under latest additions, and try to download its LilyPond file. You will get 403 Forbidden for URL that looks like this:

http://www.mutopiaproject.org/ftp/AlkanCV/O31/alkan-op31-8/alkan-op31-8.ly

Sorry if this is already known to the site maintainer.

**Comment by chrissawer** [comment]
Thanks for letting us know, I am passing this on to the owner of our server who will hopefully be able to help resolve the issue.

**Comment by robertvazan** [comment]
You might want to use some free ping service, for example uptimerobot.com. Setup one check for every type of download, pointing each to some small file of that type on the website. For text files, you can even check for presence of some short text in the file.

**Comment by dominicus** [comment]
Pages from the ftp folder seem to be serving now.

@robertvazan great idea RE: the uptime robot monitoring.  If you're OK extending your involvement, would you log this request as a new issue at our [mutopiaweb repo](https://github.com/MutopiaProject/MutopiaWeb/issues)?

**Comment by robertvazan** [comment]
Sure. Created [issue #99](https://github.com/MutopiaProject/MutopiaWeb/issues/99) on MutopiaWeb.
