### ISSUE TITLE
Missing log file for Mozart KV488, KV525

### ISSUE THREAD

**Issue by dominicus** [MutopiaProject/MutopiaProject#1042]
The change logs for these pieces are missing:

- [Mozart KV488](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=2229)
- [Mozart KV525](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=2230)

**Comment by chrissawer** [comment]
Good spot, I ran the log file generation script to fix these today
