### ISSUE TITLE
Frederick Septimus Kelly

### ISSUE THREAD

**Issue by Beacon515L** [MutopiaProject/MutopiaProject#1089]
I was considering contributing some typesettings of the works of Frederick Septimus Kelly (1881-1916, Australian) from [the public domain scores available on IMSLP](https://imslp.org/wiki/Category:Kelly%2C_Frederick_Septimus).  Mutopia does not appear to currently list him as a composer.

Should I simply create the relevant directories as part of my PR and expect someone will do whatever administrivia is necessary to list him, and then just list him as KellyF in Lilypond, or do I need to do something else first?

**Comment by glenl** [comment]
The author is added as needed when the piece is processed for publication. It seems there is a bit of a submission backlog at this time.

**Comment by Beacon515L** [comment]
Okay, cool. So I'll straight up just submit my transcriptions with _mutopiacomposer_ = 'KellyF' and be done with it. Cheers.
