### ISSUE TITLE
Remaining copyright repairs needed in several pieces

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#199]
Piece no. 481 copyright = "Copyright 2004 Diego Guillen"
no. 420 copyright = "Music: public domain; Fingering copyright 2004 Steven J. Dunlop and licensed via GFDL and CC-ASAL"
nos. 452, 453, and 413 have copyright = "Creative Commons plus audio permission"

5 pieces that don't have the proper tag and need intervention.

**Comment by dominicus** [comment]
progress to be tracked via #192
