### ISSUE TITLE
Update PachelbelJ, Fugues on the Magnificat III. 7, to LilyPond 2.14+

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#297]
Mutopia link: [Fugues on the Magnificat III. 7. by PachelbelJ (at 2.0.3)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=420)

Repository: PachelbelJ/fugue-3-7

**Do not duplicate work! Review instructions on the milestone tracker, issue# #283**

**Comment by dominicus** [comment]
together with 16538fd6fddd3b87f974921c9c3b7a0cd04fdc84, addresses Pachelbel entry in #192
