### ISSUE TITLE
New: Hanon - The Virtuoso Pianist - Part 1 (Exerc. 1-20)

### ISSUE THREAD

**Issue by dominicus** [MutopiaProject/MutopiaProject#357]
- [IMSLP Ref Page](http://imslp.org/wiki/The_Virtuoso_Pianist_(Hanon,_Charles-Louis)#IMSLP91547)
 - [PDF](http://imslp.org/wiki/Special:ImagefromIndex/00874) - Schirmer, 1900.
 - IMSLP Popularity (downloads/day): 69
 - YearComposed/Style/Instrument: 1873/Technique/Piano
 - Comments: 20 pages.  Contact organizer if you wish to typeset only a subset of this work.

**Comment by dominicus** [comment]
@stevetnz will you update on progress?

**Comment by stevetnz** [comment]
I have some work I did back in July but I haven't looked at it since then.

Would someone like to take a look and offer advice to help me finish it?

**Comment by dominicus** [comment]
in process
