### ISSUE TITLE
New: Mendelssohn - Violin Concerto in Emin (solo) Op64

### ISSUE THREAD

**Issue by dominicus** [MutopiaProject/MutopiaProject#359]
- [IMSLP Ref Page](http://imslp.org/wiki/Violin_Concerto,_Op.64_%28Mendelssohn,_Felix%29)
- [PDF](http://imslp.org/wiki/Special:ImagefromIndex/49678) - Fischer, n.d.(ca.1917)
- IMSLP Popularity (downloads/day): 55
- YearComposed/Style/Instrument: 1844/Romantic/Violin
- Comments: 14 pages

**Comment by slacy** [comment]
I've started working on this in my spare time.  It's slow going -- is there any utility in uploading this one page at a time as I finish them, or are you only interested in the complete piece?

**Comment by dominicus** [comment]
Thanks for volunteering time to typeset this popular piece. I've noted the assignment on our [tracker](https://github.com/MutopiaProject/MutopiaProject/issues/355).
You can [submit a pull request](https://github.com/MutopiaProject/MutopiaProject/wiki/Guidelines-for-new-score-submissions-using-github) when finished.

**Comment by dominicus** [comment]
@slacy, inquiring on the status for this piece
My email javier (at) ruiz-alma (dot) com

**Comment by dominicus** [comment]
@slacy, I'm closing this tracker.  Feel free to email any partial work to javier (at) ruiz-alma (dot) com.
