### ISSUE TITLE
New: Bach's Violin Concerto in A minor (violin solo) BWV 1041

### ISSUE THREAD

**Issue by dominicus** [MutopiaProject/MutopiaProject#363]
- [IMSLP Ref Page](http://imslp.org/wiki/Violin_Concerto_in_A_minor,_BWV_1041_(Bach,_Johann_Sebastian)#IMSLP56551)
 - [PDF](http://imslp.org/wiki/Special:ImagefromIndex/56551) - Reprint of Breitkopf & Härtel, n.d. by Edwin F. Kalmus, n.d.(after 1933).
 - IMSLP Popularity (downloads/day): 35 - YearComposed/Style/Instrument: 1730/Baroque/Violin
 - Comments: 6 pages.

**Comment by fedelibre** [comment]
I don't have time and motivation to complete this. It's too long and it's not my instrument.
I can keep that branch so anyone can take my work and complete it. I don't think I should send a pull request for something not finished, right?
