### ISSUE TITLE
Website: improvements to advanced search page

### ISSUE THREAD

**Issue by PaulMorris** [MutopiaProject/MutopiaProject#401]
I have some edits for the advanced search page I'd like to propose.  I got started on this by noticing that the three items at the bottom that start "Display only music..." really belong underneath the heading "Options which narrow down the range of music which is displayed".  Then I ended up coming up with a number of other improvements (at least I think so).  See the following screenshot:

-----------------------

![mutopia-advanced-search-proposal](https://cloud.githubusercontent.com/assets/1091693/3075097/f2505fa4-e363-11e3-828e-d7a50129763f.png)

-----------------------

I'm happy to submit these changes as a pull request (they are just edits to the html-in/advsearch.html-in file), but I thought it would be worth discussing this first in case there are other suggestions.

One question I have is whether it would be ok to include a css <style> block in the head of this html file (as opposed to an external css file).  The css I have introduced adds additional spacing between the lines of text and to removes the bullet points (since I do not think they are needed).  The results are shown in the screenshot.  

I would attach my html file, but it looks like github only allows image attachments.  Let me know if you would like me to send it via email, perhaps to the mailing list.

**Comment by dominicus** [comment]
Closing, as this was imlemented via https://github.com/MutopiaProject/MutopiaWeb/issues/2
