### ISSUE TITLE
Remove Lulu.com links

### ISSUE THREAD

**Issue by PaulMorris** [MutopiaProject/MutopiaProject#402]
From issue #401 
These two records:
http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=276
http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=810
Should have their "MoreInformation" page revised to remove the Lulu.com link...as this store is no longer operational.

**Comment by dominicus** [comment]
@chrissawer, checking the cited links in the first post, the lulu.com links no longer appear on the new site.
May we close this?

**Comment by chrissawer** [comment]
I had clearly missed this issue!
The lulu links no longer appear, but this is actually a bug in the perl code make-table.cgi - the relevant variables are declared local to an if statement.
I would prefer to remove this perl code and the data files before closing this issue. I will have a look at doing this.

**Comment by chrissawer** [comment]
Code now removed. Closing issue.
