### ISSUE TITLE
Update Violin Concerto in D Major (All three movements) by TchaikovskyPI

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#492]
Mutopia link: [Violin Concerto in D Major (All three movements) by TchaikovskyPI (at 2.2.5)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=466)

Repository: TchaikovskyPI/O35/tchai_op35

Part of [LilyPond update #4 milestone](https://github.com/MutopiaProject/MutopiaProject/milestones/LilyPond%20update%20%234)

**Comment by dominicus** [comment]
LaTeX?  If so, would we consider updating to LP-only?

**Comment by doughdemon** [comment]
That sounds sensible. LaTeX seems only to be used for the title page and the headings.
