### ISSUE TITLE
Update Divertissements pour la guitare, n°2 Waltz by SorF

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#494]
Mutopia link: [Divertissements pour la guitare, n°2 Waltz by SorF (at 2.2.2)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=452)

Repository: SorF/O1/sor_op1_2

Part of [LilyPond update #4 milestone](https://github.com/MutopiaProject/MutopiaProject/milestones/LilyPond%20update%20%234)

**Comment by ksnortum** [comment]
I'd like to be assigned this
