### ISSUE TITLE
Update Bethena by JoplinS

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#500]
Mutopia link: [Bethena by JoplinS (at 2.2.6)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=463)

Repository: JoplinS/bethena

Part of [LilyPond update #4 milestone](https://github.com/MutopiaProject/MutopiaProject/milestones/LilyPond%20update%20%234)

**Comment by dominicus** [comment]
closed via #563
