### ISSUE TITLE
Update Valse Op. 64, No. 1 ('Minute Waltz') by ChopinFF

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#507]
Mutopia link: [Valse Op. 64, No. 1 ('Minute Waltz') by ChopinFF (at 2.2.6)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=483)

Repository: ChopinFF/O64/chopin_valse_op64_no1

Part of [LilyPond update #4 milestone](https://github.com/MutopiaProject/MutopiaProject/milestones/LilyPond%20update%20%234)

**Comment by ksnortum** [comment]
I'd like to be assigned to this
