### ISSUE TITLE
Update Fugue fragment Anh. 41 (375g) by MozartWA

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#510]
Mutopia link: [Fugue fragment Anh. 41 (375g) by MozartWA (at 2.2.1)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=447)

Repository: MozartWA/Anh41/k375g

Part of [LilyPond update #4 milestone](https://github.com/MutopiaProject/MutopiaProject/milestones/LilyPond%20update%20%234)

**Comment by ksnortum** [comment]
I'd like to be assigned to this
