### ISSUE TITLE
Update Marche funebre KV 453a by MozartWA

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#511]
Mutopia link: [Marche funebre KV 453a by MozartWA (at 2.2.1)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=446)

Repository: MozartWA/KV453a/k453a

Part of [LilyPond update #4 milestone](https://github.com/MutopiaProject/MutopiaProject/milestones/LilyPond%20update%20%234)

**Comment by ksnortum** [comment]
I'd like to be assigned to this.
