### ISSUE TITLE
Redirect http://mutopiaproject.org to http://www.mutopiaproject.org

### ISSUE THREAD

**Issue by adius** [MutopiaProject/MutopiaProject#560]

**Comment by fedelibre** [comment]
I see that the server runs Apache.
I'm not sure what rule is best. I found [this solution](http://techstream.org/Web-Development/HTACCESS/WWW-to-Non-WWW-and-Non-WWW-to-WWW-redirect-with-HTACCESS):

```
<VirtualHost *>
  ServerName mutopiaproject.org
  Redirect 301 / http://www.mutopiaproject.org/
</VirtualHost>                    
```

**Comment by adius** [comment]
This is still an issue. The redirect looks good to me

**Comment by glenl** [comment]
If access to the virtual host file is problematic, can it be done with `.htaccess` ?

```bash
Options +Indexes
<IfModule mod_rewrite.c>
  RewriteEngine On
   RewriteCond %{HTTPS} !=on
   RewriteCond %{HTTP_HOST} !^www\..+$ [NC]
   RewriteRule ^ http://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</IfModule>
```
Requires `mod_rewrite` enabled to work but that is a typical configuration.

**Comment by adius** [comment]
It's been over a year. =D
Normally you can simply specify a redirect at your domain name provider!

**Comment by chrissawer** [comment]
Apache config changes shouldn't be a problem but I think we'd need a new A or CNAME record adding as well which might be tricker. I will try to contact the relevant people in the new year.

**Comment by fedelibre** [comment]
@chrissawer Any progress on this?

In my experience, all you need is an A record pointing to the server IP and a CNAME record for the www domain. Then you can do the redirect either way in Apache.

**Comment by ssb22** [comment]
FYI this issue should probably have been closed some time ago as the redirect is working just fine in 2024 (to https).  Yes this project does currently appear to be having some maintenance issues (see #1110) but URL redirection is not one of them.

**Comment by fedelibre** [comment]
Thanks @ssb22 
I'll close this issue.
