### ISSUE TITLE
Different versions of the same piece

### ISSUE THREAD

**Issue by joram-berger** [MutopiaProject/MutopiaProject#575]
Is it possible to have differing versions of the same piece on Mutopia? Are there objections?

I ask because of the following situation: For many scores, small changes but sometimes also large rewrites would be desirable to improve the visual quality of the output. As personal preferences are different, it might be that the original author like his score to be changed. Different versions would open an easy way to make changes without thouching the original authors work. Is this desirable? If not, which way should be chosen: The first author of a piece carved it in stone (no changes without contacting him) or improvements are welcome (might lead to discussions whether it is an improvement)?

**Comment by dominicus** [comment]
I believe there's precedent in Mutopia of pieces with more than one version.
For example, let's say Mutopia has a typeset, and you wish to introduce a new typeset aligned to a another edition of the piece (i.e. one with significant differences with respect to articulation, or other editorial differences).
I don't think there would be any issue with hosting versions of more than one edition.

Corrections and improvements to existing editions, of course, best to bring up to the maintainer attention. If no reply, log an issue, we'll get to it.  I can't remember any case of maintainer blocking improvements to released pieces, especially if you're willing to do the work.

Corrections to pitches, slurs/ties, duration values are not uncommon...log an issue or pull-request, we confirm these and apply the corrections.

If the current maintainer is agreeable, taking over the maintainer role is also an option.  The piece will still be attributed to the original typesetter, though.  See our ongoing discussion regarding management of original typesetters vs. maintainers #405 and feel free to add your thoughts on that topic.

**Comment by joram-berger** [comment]
Thanks. I close this comment as my question has been answered.
