### ISSUE TITLE
Update "Brandenburg Concerto No. 5 (3rd Movement: Allegro)" by BachJS

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#631]
The goal of this issue is to update [Mutopia piece 548](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=548) to a more recent version of LilyPond.
Mutopia link: http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=548

In your github fork, the repository location would be::

```
<fork-top>/ftp/BachJS/BWV1050/brand5-3
```

where ``fork-top`` is the top of the forked repository.

**Comment by glenl** [comment]
Assigned to joram-berger.

**Comment by joram-berger** [comment]
Done in pull request #664.
