### ISSUE TITLE
Update "SUONATA QUARTA, FVGA CROMATICA From Primo Registro of the Organo Suonarino" by BanchieriA

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#636]
The goal of this issue is to update [Mutopia piece 34](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=34) to a more recent version of LilyPond.
Mutopia link: http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=34
In your github fork, the repository location would be::
```
<fork-top>/ftp/BanchieriA/Reg1_Suon4
```
where ``fork-top`` is the top of the forked repository.

**Comment by ksnortum** [comment]
I'd like to be assigned to this issue.

**Comment by glenl** [comment]
You have been assigned this issue.
