### ISSUE TITLE
Update "SUONATA TERZA, FVGA GRAVE From Primo Registro of the Organo Suonarino" by BanchieriA

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#637]
The goal of this issue is to update [Mutopia piece 33](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=33) to a more recent version of LilyPond.
Mutopia link: http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=33
In your github fork, the repository location would be::
```
<fork-top>/ftp/BanchieriA/Reg1_Suon3
```
where ``fork-top`` is the top of the forked repository.

**Comment by ksnortum** [comment]
I'd like to be assigned to this piece.

**Comment by glenl** [comment]
You have been assigned. Thanks for volunteering!
