### ISSUE TITLE
Update "SUONATA SECONDA, FVGA TRIPLICATA From Primo Registro of the Organo Suonarino" by BanchieriA

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#638]
The goal of this issue is to update [Mutopia piece 32](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=32) to a more recent version of LilyPond.
Mutopia link: http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=32
In your github fork, the repository location would be::
```
<fork-top>/ftp/BanchieriA/Reg1_Suon2
```
where ``fork-top`` is the top of the forked repository.

**Comment by ksnortum** [comment]
I'd like to do this one.

**Comment by glenl** [comment]
I have assigned this issue with you.

Thanks!

-glen
