### ISSUE TITLE
Assign Mendelssohn Bartholdy: Nunc dimittis ("Herr, nun lässest du deinen Diener in Frieden fahren")

### ISSUE THREAD

**Issue by jonathan-scholbach** [MutopiaProject/MutopiaProject#804]
I am working on "Herr, nun lässest du deinen Diener in Frieden fahren" by Felix Mendelssohn Bartholdy (MVW 60, op. 69 No. 1). Can you please assign it to me, so that it is listed on the in-progress page? Thanks!

**Comment by glenl** [comment]
I've update the projects page with your project. This will not show up on the site until the next update.
