### ISSUE TITLE
Fix MIDI for Mendelssohn Op20 String Octet

### ISSUE THREAD

**Issue by dominicus** [MutopiaProject/MutopiaProject#965]
As reported by Ella Yu (ellaxyu -at- gmail )
MIDI for this piece rendered with percussion.
Needs fix.
As possible, update source from LP v2.6 to a later version.

**Comment by dominicus** [comment]
Knute, thanks for reviewing this one.  Please link this issue to close upon your pull request.

**Comment by ksnortum** [comment]
Resolved in branch ksnortum:Mendelssohn_O20_update.

**Comment by dominicus** [comment]
Fixed by #972
